name: Documentation
description: Report an issue with the general or code documentation of ken.
labels:
  - documentation
assignees:
  - zekrotja
body:
  - type: markdown
    attributes:
      value: Thank you for filling out this form to improve the documentation of ken! ❤️
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Short description
      description: |
        Please describe the issue with the documentation as concise as possible.
  - type: textarea
    id: attachments
    validations:
      required: false
    attributes:
      label: Attachments
      description: |
        Here you can attach image links, logs or videos to the issue. 
        Please use the [markdown notation for image files](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#images).
