name: Check Examples
on:
  workflow_dispatch:
  push:
    branches:
      - "*"
    paths-ignore:
      - "**.md"

jobs:
  check-examples:
    name: Check Examples
    runs-on: ubuntu-latest
    steps:

      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download Dependencies
        run: go mod download

      - name: Compile Examples
        run: sh scripts/build-examples.sh