name: Check Examples
on:
  workflow_dispatch:
  push:
    branches:
      - "*"
    paths-ignore:
      - "**.md"

jobs:
  check-examples:
    name: Check Examples
    runs-on: ubuntu-latest
    steps:

      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download Dependencies
        run: go get -v -t -d ./...

      - name: Compile Examples
        run: |
          go build -v examples/basic/main.go
          go build -v examples/middlewares/main.go